[[ContinuousIntegrationWithToadEdgePlugin-Compatibilitymatrix]]
== Compatibility matrix

[cols=",",options="header",]
|===
|Plugin version |Toad Edge^TM^ version
|2.2|2.0.x, 2.1.x, 2.2.x, 2.3.x
|===

[[ContinuousIntegrationWithToadEdgePlugin-Introduction]]
== Introduction

This plugin allows user to automate Database Lifecycle Management tasks
from within Jenkins. Following tasks are available:

. Compare database schemas - Compare two different schemas (from
database, model or snapshot). Based on it you can do in the next steps
further actions (like generating report or alter script)
. Compare database with baseline - Compare your current schema with
baseline. In case the schema is different the build step will fail.
. Create baseline - Set the current state of your schema as the baseline
to detect any changes that has been made into the schema since now.
. Create snapshot - Save your database schema to a file to have the
possibility to return to it later.
. Deploy SQL script - Execute any arbitrary SQL script on a selected
database.
. Generate Jenkins HTML comparison report - Generate a HTML report based
on a previous schema compare build step. This report is accessible via
build detail within build history in Jenkins.
. Generate standalone HTML comparison report - Generate a HTML report
based on a previous schema compare build step. 
. Generate change SQL script - Generate an alter SQL script based on a
previous schema compare build step.
. Generate create SQL script - Generate a create SQL script from your
VCS repository, saved snapshot or database.

[[ContinuousIntegrationWithToadEdgePlugin-Installing]]
== Installing

First you need to install the plugin.

. Open your Jenkins.
. Go to Manage Jenkins > Manage Plugins > Available and search for
Continuous Integration with Toad Edge^TM^.
. Check the Continuous Integration with Toad Edge^TM^, and finish
installation

In order for plugin to work properly it needs Continuous Integration
with Toad Edge CLI libraries. Those are distributed as .zip file. To
make it work:

. Upload libraries to your jenkins master node
. Go to Manage Jenkins -> Configure System and look for Continuous
Integration with Toad Edge section
. Fill-in path to libraries to "Continuous Integration with Toad
Edge^TM^ libraries .zip file" field
. Save

[[ContinuousIntegrationWithToadEdgePlugin-Documentation]]
== Documentation

Documentation for Continuous Integration with Toad Edge^TM^ can be found
on Quest Software Inc. pages.

[cols=",",options="header",]
|===
|Plugin version |Documentation link

|2.2 a|
http://support.quest.com/technical-documents/toad-edge/2.0.2/user-guide/continuous-integration-and-delivery

http://support.quest.com/technical-documents/toad-edge/2.1/user-guide/continuous-integration-and-delivery

https://support.quest.com/technical-documents/toad-edge/2.2/user-guide/continuous-integration-and-delivery

|===
